"""Menu seed data generated from `data/Menu Abhimata Cafe.xlsx`.

Regenerate by running `python _gen_seed.py` in the backend directory
after updating the Excel file.
"""

MENU_SEED = [{'name': 'Nasi Goreng Abhimata',
  'category': 'Food',
  'description': 'Ayam Goreng, Telor, Acar, dan Kerupuk',
  'price': 35000.0},
 {'name': 'Nasi Goreng',
  'category': 'Food',
  'description': 'Telor, Acar, dan Kerupuk',
  'price': 25000.0},
 {'name': 'Nasi Goreng Kampung',
  'category': 'Food',
  'description': 'Bilis, Telor, Acar, dan Kerupuk',
  'price': 25000.0},
 {'name': 'Nasi Goreng Seafood',
  'category': 'Food',
  'description': 'Udang, Sotong, Baso Ikan, Telor, Acar, dan Kerupuk',
  'price': 35000.0},
 {'name': 'Nasi Goreng Cabe hijau',
  'category': 'Food',
  'description': 'Telor, Acar, dan Kerupuk',
  'price': 25000.0},
 {'name': 'Indomie Goreng', 'category': 'Food', 'description': 'Telor dan Timun', 'price': 15000.0},
 {'name': 'Indomie Rebus Abhimata',
  'category': 'Food',
  'description': 'Resep spesial pakai telor',
  'price': 15000.0},
 {'name': 'Mie Goreng Abhimata',
  'category': 'Food',
  'description': 'Telor, Acar, dan Kerupuk',
  'price': 25000.0},
 {'name': 'Kwetiaw Abhimata',
  'category': 'Food',
  'description': 'Telor, Acar, dan Kerupuk',
  'price': 30000.0},
 {'name': 'Bihun Goreng Abhimata',
  'category': 'Food',
  'description': 'Telor, Acar, dan Kerupuk',
  'price': 30000.0},
 {'name': 'Ayam Bakar',
  'category': 'Food',
  'description': 'Ayam, Nasi, Sambal, Sayur Asem, dan Lalapan',
  'price': 30000.0},
 {'name': 'Ayam Penyet',
  'category': 'Food',
  'description': 'Ayam, Nasi, Lalapan',
  'price': 30000.0},
 {'name': 'Ayam Cabe Hijau',
  'category': 'Food',
  'description': 'Ikan Pepes, Nasi',
  'price': 30000.0},
 {'name': 'Ikan Pepes',
  'category': 'Food',
  'description': 'Ceker dan Ayam suwir',
  'price': 30000.0},
 {'name': 'Soto Ceker',
  'category': 'Food',
  'description': 'Daging atau Ayam, Nasi, dan Kerupuk',
  'price': 25000.0},
 {'name': 'Soto Medan', 'category': 'Food', 'description': None, 'price': 30000.0},
 {'name': 'Nasi Putih', 'category': 'Food', 'description': None, 'price': 5000.0},
 {'name': 'Kerupuk', 'category': 'Food', 'description': None, 'price': 5000.0},
 {'name': 'Bakwan Jagung', 'category': 'Snacks', 'description': None, 'price': 15000.0},
 {'name': 'Bakwan Sayur Udang', 'category': 'Snacks', 'description': None, 'price': 15000.0},
 {'name': 'Jemput-Jemput Pisang', 'category': 'Snacks', 'description': None, 'price': 15000.0},
 {'name': 'Rondo Royal', 'category': 'Snacks', 'description': None, 'price': 15000.0},
 {'name': 'Kentang Goreng', 'category': 'Snacks', 'description': None, 'price': 20000.0},
 {'name': 'Keju Kentang Stick', 'category': 'Snacks', 'description': None, 'price': 25000.0},
 {'name': 'Nugget', 'category': 'Snacks', 'description': None, 'price': 20000.0},
 {'name': 'Pisang Goreng', 'category': 'Snacks', 'description': None, 'price': 15000.0},
 {'name': 'Pisang Keju Cokelat', 'category': 'Snacks', 'description': None, 'price': 25000.0},
 {'name': 'Sosis Bakar atau Goreng', 'category': 'Snacks', 'description': None, 'price': 20000.0},
 {'name': 'Teh O', 'category': 'Drinks', 'description': None, 'price': 12000.0},
 {'name': 'Teh Obeng', 'category': 'Drinks', 'description': None, 'price': 14000.0},
 {'name': 'Teh Tarik (Hot)', 'category': 'Drinks', 'description': None, 'price': 17000.0},
 {'name': 'Teh Tarik (Cold)', 'category': 'Drinks', 'description': None, 'price': 22000.0},
 {'name': 'Air Jeruk (Hot)', 'category': 'Drinks', 'description': None, 'price': 15000.0},
 {'name': 'Air Jeruk (Cold)', 'category': 'Drinks', 'description': None, 'price': 20000.0},
 {'name': 'Matcha', 'category': 'Drinks', 'description': None, 'price': 25000.0},
 {'name': 'Chocolate', 'category': 'Drinks', 'description': None, 'price': 25000.0},
 {'name': 'Milo Susu (Hot)', 'category': 'Drinks', 'description': None, 'price': 17000.0},
 {'name': 'Milo Susu (Cold)', 'category': 'Drinks', 'description': None, 'price': 22000.0},
 {'name': 'Lemon Tea (Hot)', 'category': 'Drinks', 'description': None, 'price': 17000.0},
 {'name': 'Lemon Tea (Cold)', 'category': 'Drinks', 'description': None, 'price': 20000.0},
 {'name': 'Kopi O', 'category': 'Drinks', 'description': None, 'price': 10000.0},
 {'name': 'Kopi Obeng', 'category': 'Drinks', 'description': None, 'price': 13000.0},
 {'name': 'Kopi Susu Abhimata (Hot)', 'category': 'Drinks', 'description': None, 'price': 15000.0},
 {'name': 'Kopi Susu Abhimata (Cold)', 'category': 'Drinks', 'description': None, 'price': 18000.0},
 {'name': 'Orange Squash', 'category': 'Drinks', 'description': None, 'price': 30000.0},
 {'name': 'Mango Yakult', 'category': 'Drinks', 'description': None, 'price': 30000.0},
 {'name': 'Orange Yakult', 'category': 'Drinks', 'description': None, 'price': 30000.0},
 {'name': 'Es Bandung', 'category': 'Drinks', 'description': None, 'price': 18000.0},
 {'name': 'Sirup Merah', 'category': 'Drinks', 'description': None, 'price': 15000.0},
 {'name': 'Lychee Tea', 'category': 'Drinks', 'description': None, 'price': 30000.0},
 {'name': 'Mineral Water', 'category': 'Drinks', 'description': None, 'price': 5000.0},
 {'name': 'Extra Joss Susu', 'category': 'Drinks', 'description': None, 'price': 18000.0}]
